<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vm" nsURI="org.bigraphs" nsPrefix="bigraphMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="BPlace" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bChild" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BPlace" containment="true" eOpposite="vm.ecore#//BPlace/bPrnt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPrnt" eType="ecore:EClass vm.ecore#//BPlace"
        eOpposite="vm.ecore#//BPlace/bChild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BRoot" eSuperTypes="vm.ecore#//BPlace vm.ecore#//IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass vm.ecore#//BBigraph" eOpposite="vm.ecore#//BBigraph/bRoots"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BNode" eSuperTypes="vm.ecore#//BPlace vm.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPorts" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BPort" containment="true" eOpposite="vm.ecore#//BPort/bNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass vm.ecore#//EStringToEJavaObjectMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BSite" eSuperTypes="vm.ecore#//BPlace vm.ecore#//IndexableType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bLink" eType="ecore:EClass vm.ecore#//BLink"
        eOpposite="vm.ecore#//BLink/bPoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BLink" abstract="true" eSuperTypes="vm.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPoints" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BPoint" eOpposite="vm.ecore#//BPoint/bLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPort" eSuperTypes="vm.ecore#//BPoint vm.ecore#//IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bNode" lowerBound="1" eType="ecore:EClass vm.ecore#//BNode"
        eOpposite="vm.ecore#//BNode/bPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BInnerName" eSuperTypes="vm.ecore#//BPoint vm.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass vm.ecore#//BBigraph" eOpposite="vm.ecore#//BBigraph/bInnerNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEdge" eSuperTypes="vm.ecore#//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass vm.ecore#//BBigraph" eOpposite="vm.ecore#//BBigraph/bEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOuterName" eSuperTypes="vm.ecore#//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass vm.ecore#//BBigraph" eOpposite="vm.ecore#//BBigraph/bOuterNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameableType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexableType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BBigraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bRoots" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BRoot" containment="true" eOpposite="vm.ecore#//BRoot/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bEdges" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BEdge" containment="true" eOpposite="vm.ecore#//BEdge/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bInnerNames" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BInnerName" containment="true" eOpposite="vm.ecore#//BInnerName/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bOuterNames" upperBound="-1"
        eType="ecore:EClass vm.ecore#//BOuterName" containment="true" eOpposite="vm.ecore#//BOuterName/bBigraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToEJavaObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coin" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="VM" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Button1" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Button2" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pressed" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coffee" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tea" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PHD" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wallet" eSuperTypes="vm.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tresor" eSuperTypes="vm.ecore#//BNode"/>
</ecore:EPackage>
